### ISSUE TITLE
Github CI fails when docker is on and keep_local_envs_in_vcs is off

### ISSUE THREAD

**Issue by johnnymetz** [cookiecutter/cookiecutter-django#5319]
## What happened?

Github CI fails when local envs is not kept. 

<img width="1158" alt="Screenshot 2024-08-23 at 11 21 12 PM" src="https://github.com/user-attachments/assets/4c882912-208a-4521-9e5e-5153584f137c">

I think we need to remove these lines in Github CI: https://github.com/cookiecutter/cookiecutter-django/blob/f947c612faf1d612bc357de57b6900e7fea65850/%7B%7Bcookiecutter.project_slug%7D%7D/docker-compose.local.yml#L23-L25

## What should've happened instead?

Github CI should pass.

## Additional details

- Host system configuration:

  - Version of cookiecutter CLI (get it with `cookiecutter --version`): 2.6.0
  - OS name and version:

    On Linux, run

    ```bash
    lsb_release -a 2> /dev/null || cat /etc/redhat-release 2> /dev/null || cat /etc/*-release 2> /dev/null || cat /etc/issue 2> /dev/null
    ```

    On MacOs, run

    ```bash
    sw_vers
    ```

    On Windows, via CMD, run

    ```
    systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
    ```

    ```bash
    ProductName:		macOS
    ProductVersion:		14.5
    BuildVersion:		23F79

    ```

  - Python version, run `python3 -V`: 3.12.4
  - Docker version (if using Docker), run `docker --version`: Docker version 27.1.1, build 6312585
  - docker compose version (if using Docker), run `docker compose --version`: Docker Compose version v2.29.1-desktop.1

- Options selected and/or [replay file](https://cookiecutter.readthedocs.io/en/latest/advanced/replay.html):
  On Linux and macOS: `cat ${HOME}/.cookiecutter_replay/cookiecutter-django.json`
  (Please, take care to remove sensitive information)

```json
use_docker: y
keep_local_envs_in_vcs: n
```

<summary>
Logs:
<details>
<pre>
$ cookiecutter https://github.com/cookiecutter/cookiecutter-django
project_name [Project Name]: ...
</pre>
</details>
</summary>

**Comment by dominiqueplante** [comment]
@johnnymetz - can you point me to where you got the 'Build the Stack screenshot? I've been looking.

For resolution, instead of removing the lines in `docker-compose.local.yml`, would wrapping the block in a conditional also be another way to resolve, i.e:

``` yaml
{%- if cookiecutter.keep_local_envs_in_vcs == 'y' %}
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
{%- endif %}
```

**Comment by johnnymetz** [comment]
The screenshot in is GitHub CI. The step name may have changed. This issue is almost a year old.

**Comment by dominiqueplante** [comment]
What did you think of my suggestion @johnnymetz ?

**Comment by dominiqueplante** [comment]
Re screenshot, I was pretty sure it was in the actions, so that helps track it down - we should be able to see state of the folder when you created the issue and look at when the action got renamed.

**Comment by johnnymetz** [comment]
Suggestion sounds good. I'm no longer using this project so I cant test/verify. Probably good to close this issue.

**Comment by browniebroke** [comment]
> For resolution, instead of removing the lines in `docker-compose.local.yml`, would wrapping the block in a conditional also be another way to resolve, i.e:
> 
> {%- if cookiecutter.keep_local_envs_in_vcs == 'y' %}
>     env_file:
>       - ./.envs/.local/.django
>       - ./.envs/.local/.postgres
> {%- endif %}

The idea of `keep_local_envs_in_vcs` is to have the files locally on the user file system, but not in source control, so I think we would want to keep these in the compose config to run the tests locally. We would need to find a way to create these files on CI before using them...

Or use another option altogether e.g. https://github.com/cookiecutter/cookiecutter-django/issues/1258

**Comment by dominiqueplante** [comment]
Yes it's generally best practice not to put secrets in source control, which again raises the issue of how to set up these files in CI.

**Comment by an1uk** [comment]
I added the below to ci.yml and it then passed ci (after I fixed an actual issue with my code).

I'm not particularly versed in Django, Cookiecutter, or CI, so this may not be the best approach. 

Edit: I can't get the top bit to display within the code section for some reason.

`      
        - name: Create dummy .envs/.local/.django and .postgres if missing
        run: |
          mkdir -p .envs/.local

          if [ ! -f .envs/.local/.django ]; then
            cat <<EOF > .envs/.local/.django
          # General
          USE_DOCKER=true
          IPYTHONDIR=/app/.ipython

          # Redis
          REDIS_URL=redis://redis:6379/0

          # Celery
          CELERY_FLOWER_USER=dummy_user
          CELERY_FLOWER_PASSWORD=dummy_password

          # Django
          DJANGO_DEBUG=True
          DATABASE_URL=postgres://dummy_user:dummy_password@postgres:5432/dummy_db
          EOF
              fi

              if [ ! -f .envs/.local/.postgres ]; then
                cat <<EOF > .envs/.local/.postgres
          POSTGRES_HOST=postgres
          POSTGRES_PORT=5432
          POSTGRES_DB=dummy_db
          POSTGRES_USER=dummy_user
          POSTGRES_PASSWORD=dummy_password
          EOF
              fi
`

**Comment by EllaSharakanski** [comment]
Any resolution here? I'm new to cookiecutter-django and stuck with a failing CI because pytest cannot read the env vars (since they are not committed).

What is the official recommended solution? Currently this doesn't work out of the box.

**Comment by Africanus12** [comment]
I've opened a PR with a complete fix for this:
- `required: false` on env_file entries in docker-compose.local.yml and docker-compose.docs.yml
- CI step that creates minimal dummy .envs/.local files when they are missing

Builds on the approach in #6222 by also ensuring Postgres/Django get required variables in CI.

**Comment by Africanus12** [comment]
I've opened a PR with a complete fix for this: https://github.com/cookiecutter/cookiecutter-django/pull/6817

It:
1. Marks `env_file` entries as `required: false` in `docker-compose.local.yml` and `docker-compose.docs.yml`
2. Adds a CI step that creates minimal dummy `.envs/.local` files when they are absent (so Postgres/Django still get the required variables)

This builds on the approach in #6222. All upstream CI checks on the PR are currently green.
